# Generated by Django 4.1.4 on 2022-12-20 16:45

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_options_options",
                    models.ManyToManyField(
                        related_name="brand_options", to="form.brand"
                    ),
                ),
                (
                    "brands_seen_options",
                    models.ManyToManyField(related_name="brands_seen", to="form.brand"),
                ),
                (
                    "prod_used_options",
                    models.ManyToManyField(related_name="prod_used", to="form.brand"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.brand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_block", models.BooleanField()),
                ("youtube_sub", models.BooleanField()),
                ("youtube_mobile", models.IntegerField()),
                (
                    "apprise",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("1", "Primarily friends and family"),
                            ("2", "Amazon, Flipkart or any other e-commerce stores"),
                            (
                                "3",
                                "Television and OTT Platform Ads (like Youtube, Netflix, Hotstar, etc)",
                            ),
                            ("4", "Email Ads"),
                            ("5", "Store Visits"),
                            ("6", "Website Ads"),
                            ("7", "I primarily search for products"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "brands_seen",
                    models.ManyToManyField(
                        related_name="intro_brands_seen", to="form.brand"
                    ),
                ),
                (
                    "experience",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.experience",
                    ),
                ),
                (
                    "prod_used",
                    models.ManyToManyField(
                        related_name="intro_prod_used", to="form.brand"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="videos",
            field=models.ManyToManyField(to="form.video"),
        ),
    ]
