# Generated by Django 4.2.4 on 2023-08-27 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze', models.IntegerField(default=0)),
                ('cc_v', models.IntegerField()),
                ('audio_seen', models.ManyToManyField(related_name='audio_seen_options', to='form.audioclip')),
                ('brand_recog', models.ManyToManyField(related_name='brand_recog_options', to='form.brand')),
                ('brands_seen_options', models.ManyToManyField(related_name='brands_seen', to='form.brand')),
                ('prod_used_options', models.ManyToManyField(related_name='prod_used', to='form.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('desc', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.brand')),
            ],
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.video')),
            ],
        ),
        migrations.CreateModel(
            name='UserStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mage_id', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('brand_recog', models.ManyToManyField(related_name='brand_options', to='form.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SceneQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.videoscene')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_before', models.BooleanField()),
                ('seen_brand_before', models.BooleanField()),
                ('heard_before', models.BooleanField()),
                ('clear_product', models.BooleanField()),
                ('clear_brand', models.BooleanField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.video')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_block', models.BooleanField()),
                ('youtube_sub', models.BooleanField()),
                ('youtube_mobile', models.IntegerField()),
                ('apprise', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Primarily friends and family'), ('2', 'Amazon, Flipkart or any other e-commerce stores'), ('3', 'Television and OTT Platform Ads (like Youtube, Netflix, Hotstar, etc)'), ('4', 'Email Ads'), ('5', 'Store Visits'), ('6', 'Website Ads'), ('7', 'I primarily search for products')], max_length=100)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('brands_seen', models.ManyToManyField(related_name='intro_brands_seen', to='form.brand')),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.experience')),
                ('prod_used', models.ManyToManyField(related_name='intro_prod_used', to='form.brand')),
            ],
        ),
        migrations.CreateModel(
            name='GazeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_x', models.TextField(blank=True)),
                ('gaze_y', models.TextField(blank=True)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.video')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='scene_seen',
            field=models.ManyToManyField(related_name='scene_seen_options', to='form.videoscene'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='videos',
            field=models.ManyToManyField(to='form.video'),
        ),
        migrations.CreateModel(
            name='ConsistencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrandQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_types', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Narration'), (1, 'Background Music'), (2, 'Silent'), (3, "Don't Remember")], max_length=100)),
                ('prod_usage', models.IntegerField()),
                ('used_before', models.BooleanField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDescQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_description_option_out', models.ManyToManyField(to='form.video')),
            ],
        ),
        migrations.CreateModel(
            name='AudioClipQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('seek_time', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('audio_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.audioclip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audioclip',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.video'),
        ),
    ]
