# Generated by Django 4.1.4 on 2022-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="brand_options_options",
            new_name="brand_recog",
        ),
        migrations.AddField(
            model_name="video",
            name="keyframe_path",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
