# Generated by Django 4.1.4 on 2022-12-24 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0002_rename_brand_options_options_experience_brand_recog_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="path",
            new_name="src",
        ),
        migrations.AddField(
            model_name="video",
            name="length",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Popup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_before", models.BooleanField()),
                ("seen_brand_before", models.BooleanField()),
                ("heard_before", models.BooleanField()),
                ("clear_product", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.video"
                    ),
                ),
            ],
        ),
    ]
