# Generated by Django 4.2.4 on 2023-08-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_attentioncheckmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttentionCheckModel',
        ),
    ]
