# Generated by Django 4.1.4 on 2022-12-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_gazemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gazemodel",
            name="gaze",
        ),
        migrations.AddField(
            model_name="gazemodel",
            name="gaze_x",
            field=models.TextField(default="0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gazemodel",
            name="gaze_y",
            field=models.TextField(default="0"),
            preserve_default=False,
        ),
    ]
