# Generated by Django 4.1.4 on 2022-12-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_remove_gazemodel_gaze_gazemodel_gaze_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gazemodel",
            name="gaze_x",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gazemodel",
            name="gaze_y",
            field=models.TextField(blank=True),
        ),
    ]
