# Generated by Django 4.1.4 on 2022-12-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0007_userstage_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="gaze",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
