# Generated by Django 4.1.4 on 2022-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_experience_gaze"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="gaze",
            field=models.IntegerField(default=0),
        ),
    ]
