# Generated by Django 4.1.4 on 2022-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0009_alter_experience_gaze"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstage",
            name="stage",
            field=models.IntegerField(default=0),
        ),
    ]
