# Generated by Django 4.1.4 on 2022-12-26 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0010_alter_userstage_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="brand_recog",
            field=models.ManyToManyField(
                related_name="brand_recog_options", to="form.brand"
            ),
        ),
        migrations.CreateModel(
            name="VideoScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyframe_path", models.CharField(max_length=100)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.video"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_recog",
                    models.ManyToManyField(
                        related_name="brand_options", to="form.brand"
                    ),
                ),
                (
                    "scene_recog",
                    models.ManyToManyField(
                        related_name="scene_options", to="form.videoscene"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_types", models.CharField(max_length=100)),
                ("prod_usage", models.IntegerField()),
                ("used_before", models.BooleanField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.brand"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
