# Generated by Django 4.1.4 on 2022-12-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0011_alter_experience_brand_recog_videoscene_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="keyframe_path",
        ),
    ]
