# Generated by Django 4.1.4 on 2022-12-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0012_remove_video_keyframe_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyquestionnaire",
            name="scene_recog",
        ),
        migrations.DeleteModel(
            name="VideoScene",
        ),
    ]
