# Generated by Django 4.1.4 on 2022-12-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0013_remove_surveyquestionnaire_scene_recog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene", models.CharField(max_length=100)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.video"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="scene_seen",
            field=models.ManyToManyField(
                related_name="scene_seen_options", to="form.videoscene"
            ),
        ),
    ]
