# Generated by Django 4.1.4 on 2022-12-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0014_videoscene_experience_scene_seen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoscene",
            old_name="scene",
            new_name="url",
        ),
    ]
