# Generated by Django 4.1.4 on 2022-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0015_rename_scene_videoscene_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestionnaire",
            name="scene_recog",
            field=models.ManyToManyField(
                related_name="scene_options", to="form.videoscene"
            ),
        ),
    ]
