# Generated by Django 4.1.4 on 2022-12-28 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0016_surveyquestionnaire_scene_recog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BrandQuestionnaire",
            new_name="BrandQA",
        ),
        migrations.DeleteModel(
            name="SurveyQuestionnaire",
        ),
    ]
