# Generated by Django 4.1.4 on 2022-12-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0018_sceneqa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sceneqa",
            name="scene",
        ),
        migrations.RemoveField(
            model_name="sceneqa",
            name="seen",
        ),
        migrations.AddField(
            model_name="sceneqa",
            name="scenes",
            field=models.ManyToManyField(to="form.videoscene"),
        ),
    ]
