# Generated by Django 4.1.4 on 2022-12-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0019_remove_sceneqa_scene_remove_sceneqa_seen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sceneqa",
            name="scenes",
        ),
        migrations.AddField(
            model_name="sceneqa",
            name="scene",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="form.videoscene",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sceneqa",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
