# Generated by Django 4.1.4 on 2023-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0022_calibration"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandqa",
            name="scene_description",
            field=models.CharField(default="Nil", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="introduction",
            name="submit_duration",
            field=models.IntegerField(default=0),
        ),
    ]
