# Generated by Django 4.1.4 on 2023-01-24 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0023_brandqa_scene_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandqa",
            name="submit_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="popup",
            name="submit_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sceneqa",
            name="submit_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="surveyqa",
            name="submit_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ConsistencyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField()),
                ("submit_duration", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
