# Generated by Django 4.1.4 on 2023-01-24 17:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0025_brandqa_scene_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandqa",
            name="scene_options",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, "SD1"), (1, "SD2"), (2, "SD3"), (3, "SD4"), (4, "SD5")],
                max_length=1000,
            ),
        ),
    ]
