# Generated by Django 4.1.4 on 2023-01-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0026_alter_brandqa_scene_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brandqa",
            old_name="scene_options",
            new_name="scene_options_out",
        ),
        migrations.AddField(
            model_name="brandqa",
            name="scene_options_in",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="video",
            name="desc",
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
