# Generated by Django 4.1.4 on 2023-01-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0028_remove_brandqa_scene_options_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="exp_start",
        ),
        migrations.AddField(
            model_name="experience",
            name="cc_v",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consistency_check_video",
                to="form.video",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="videos",
            field=models.ManyToManyField(related_name="videos", to="form.video"),
        ),
    ]
