# Generated by Django 4.1.4 on 2023-01-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0029_remove_experience_exp_start_experience_cc_v_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="cc_v",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="videos",
            field=models.ManyToManyField(to="form.video"),
        ),
    ]
