# Generated by Django 4.1.4 on 2023-03-20 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0030_alter_experience_cc_v_alter_experience_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.video"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioClipQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("seek_time", models.IntegerField(default=0)),
                ("submit_time", models.DateTimeField(auto_now=True)),
                (
                    "audio_clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.audioclip"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="audio_seen",
            field=models.ManyToManyField(
                related_name="audio_seen_options", to="form.audioclip"
            ),
        ),
    ]
