# Generated by Django 4.1.4 on 2023-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0031_audioclip_audioclipqa_experience_audio_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandqa",
            name="scene_description",
        ),
        migrations.AddField(
            model_name="audioclip",
            name="end",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audioclip",
            name="start",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyqa",
            name="mage_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
